"""empty message

Revision ID: 22d0dd358c16
Revises: 4e5a7a432c96
Create Date: 2024-07-07 16:48:58.250610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d0dd358c16'
down_revision = '4e5a7a432c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend-requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sender_avatar', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend-requests', schema=None) as batch_op:
        batch_op.drop_column('sender_avatar')
        batch_op.drop_column('sender_username')

    # ### end Alembic commands ###
