"""Added friend count, country and banner

Revision ID: 23c0a4432ad0
Revises: 73687c4128ad
Create Date: 2024-06-21 19:02:01.539082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c0a4432ad0'
down_revision = '73687c4128ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('friend_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('banner', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner')
        batch_op.drop_column('friend_count')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
