"""Added vector column

Revision ID: 4e3c79c18e07
Revises: 22d0dd358c16
Create Date: 2024-08-06 19:33:55.183140

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '4e3c79c18e07'
down_revision = '22d0dd358c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('data_embedding')

    # ### end Alembic commands ###
