"""Added UserTopGenres model

Revision ID: 4e5a7a432c96
Revises: 23c0a4432ad0
Create Date: 2024-06-27 18:40:13.135678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e5a7a432c96'
down_revision = '23c0a4432ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users-top-genres',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users-top-genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users-top-genres_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users-top-genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users-top-genres_user_id'))

    op.drop_table('users-top-genres')
    # ### end Alembic commands ###
