"""empty message

Revision ID: 68dea295c6c0
Revises: d20a5048716c
Create Date: 2024-04-16 19:17:24.897120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dea295c6c0'
down_revision = 'd20a5048716c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track-artists',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track-artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track-artists_track_id'), ['track_id'], unique=False)

    op.create_table('users-top-tracks',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('position_for_user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users-top-tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users-top-tracks_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users-top-tracks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users-top-tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users-top-tracks_user_id'))
        batch_op.drop_index(batch_op.f('ix_users-top-tracks_track_id'))

    op.drop_table('users-top-tracks')
    with op.batch_alter_table('track-artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track-artists_track_id'))

    op.drop_table('track-artists')
    op.drop_table('tracks')
    # ### end Alembic commands ###
