"""added json fields

Revision ID: b4018b4001a0
Revises: 68dea295c6c0
Create Date: 2024-06-06 18:30:08.003164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4018b4001a0'
down_revision = '68dea295c6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artists', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('users-top-artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artists', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('next_update', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_users-top-artists_artist_id')
        batch_op.drop_constraint('users-top-artists_artist_id_fkey', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('position_for_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users-top-artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_for_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artist_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users-top-artists_artist_id_fkey', 'artists', ['artist_id'], ['id'])
        batch_op.create_index('ix_users-top-artists_artist_id', ['artist_id'], unique=False)
        batch_op.drop_column('next_update')
        batch_op.drop_column('artists')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('artists')

    # ### end Alembic commands ###
