name: Run DB Migrations

on:
  push:
    branches:
      - dev
    paths:
      - 'models/**'

jobs:
  db-migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask DB Migrations
      run: |
        export FLASK_APP=app.py
        flask db migrate
        flask db upgrade